MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

MyBlog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # List all posts
    path('', views.PostListView.as_view(), name='post_list'),

    # View a single post's details
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),

    # Create a new post
    path('create/', views.PostCreateView.as_view(), name='post_create'),

    # Edit an existing post
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),

    # Delete a post
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    
    # Search a post
    path('search/', views.PostSearchView.as_view(), name='post_search'),

    # url for REST API view
    path('api/', views.PostAPIView.as_view(), name='post-list'),
]

MyBlog/blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)  # A character field for the post title
    content = models.TextField()  # A text field for the post content.
    created_at = models.DateTimeField(default=timezone.now, editable=False)  # Editable is false, bcs this cannot be editable
    updated_at = models.DateTimeField(auto_now=True)  # automatically updates the date and time when a post is edited.

    def __str__(self):  # method is used to represent the Post objects as strings, typically in the admin interface. if anyone prints that out
        return self.title
    

MyBlog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.core.paginator import Paginator
from .models import Post
from django.urls import reverse_lazy
from rest_framework import generics
from .serializers import PostSerializer

# Create your views here.
class PostListView(ListView):  # it inherits from ListView class
    # ListView places the objects from the database in a context variable named object_list
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 12  # Implement pagination in the list view to display a limited number of posts per page.

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'  #
    context_object_name = 'post'

class PostCreateView(CreateView):
    model = Post
    template_name = 'blog/post_form.html'  #
    fields = ['title', 'content']  # 
    success_url = reverse_lazy('blog:post_list')  # class PostListView(ListView):  # it inherits from ListView class
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'  #
    context_object_name = 'post'

class PostCreateView(CreateView):
    model = Post
    template_name = 'blog/post_form.html'  #
    fields = ['title', 'content']  # 
    success_url = reverse_lazy('blog:post_list')
    
class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_form.html'  #
    fields = ['title', 'content']  # 
    success_url = reverse_lazy('blog:post_list')  # redirect him back to the list of all blog posts

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'  #
    success_url = reverse_lazy('blog:post_list')  # redirect him back to the list of all blog posts
    
class PostUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_form.html'  #
    fields = ['title', 'content']  # 
    success_url = reverse_lazy('blog:post_list')  # redirect him back to the list of all blog posts

class PostDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'  #
    success_url = reverse_lazy('blog:post_list')  # redirect him back to the list of all blog posts

# Adding search functionality
class PostSearchView(ListView):
    model = Post
    template_name = 'blog/post_search_results.html'
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('q')  # Get the search query from the URL parameter
        if query:
            return Post.objects.filter(title__icontains=query)
        return Post.objects.none()  # Return an empty queryset if no search query is provided

# REST API view
class PostAPIView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    

MyBlog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link rel = "stylesheet" href = "{% static 'style2.css' %}">
    <title>Ragnar Blog</title>
</head>
<body>
    <header>
        <h1>Ragnar Blog</h1>
    </header>

    <main>
        {% block content %}
        {% endblock %}
        <br>
    </main>

    <footer>
        &copy; 2023 Ragnar Blog
    </footer>
</body>
</html>

MyBlog/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Confirm Delete</h2>
<p>Are you sure you want to delete "{{ object.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
    <a href="{% url 'blog:post_list' %}" class="cancel-button">Cancel</a>
</form>
{% endblock %}

MyBlog/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>{{ object.title }}</h2>
<p>{{ object.content }}</p>
<p>Created on: {{ object.created_at }}</p>
<!--Adding button for quick edit that post-->
<a href="{% url 'blog:post_edit' object.pk %}" class="search-button">Edit that post</a>
<!--Adding button for quick delete that post-->
<a href="{% url 'blog:post_delete' object.pk %}" class="del1-button">Delete that post</a>

{% endblock %}

MyBlog/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="search-button" type="submit">Create post</button>
</form>
{% endblock %}

MyBlog/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
<h3>Here are the list of all blog posts: </h3>
<ul>
    {% for post in object_list %}
        <li><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
<a href="{% url 'blog:post_create' %}" class="search-button">Create New Post</a><!--here we point to the PostCreateView using the URL name 'blog:post_create'-->

{% endblock %}

MyBlog/blog/templates/blog/post_search_results.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Search Results</h1>
    <form method="GET" action="{% url 'blog:post_search' %}">
        <input type="text" name="q" placeholder="Search by title"><!--creates a text input field, 
            name attribute is set to "q," which will be used to capture the search query entered by the user.-->
        <button  class="search-button" type="submit">Search</button>
        <!--When the user clicks this button, the form will be submitted, triggering the search functionality-->
    </form>
    <ul><!--unordered list that will contain the search results-->
        {% for post in posts %}
            <li><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}